name: Daily Commit

on:
  schedule:
  - cron: '*/10 * * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create commit
        run: |
          echo "Automatic daily commit" >> daily_commit.txt
          git config --local user.email "gms8757@naver.com"
          git config --local user.name "Gaeduck-0908"
          git add daily_commit.txt
          git commit -m "Daily commit $(date +'%Y-%m-%d %H:%M:%S')"
          git push
